### ISSUE TITLE
Documentation / HowTo

### ISSUE THREAD

**Issue by marc-gist** [woolfg/mysql-backup-sidecar#11]
This looks awesome and I think is what I need for my meriamdb inside a docker.
However, I'm not great with docker and I'm having dificulty understanding the settings.
i.e. how do you pass in the password for the user?
Could you provide some sample `docker run ...` commands?

Thanks!

**Comment by luzrain** [comment]
You should better use docker-compose instead of docker run. [Some sample you can find here](https://wolfgang.gassler.org/docker-image-mysql-mariadb-backups/).

**Comment by woolfg** [comment]
thanks @marc-gist for the proposal. It is always good to have more documentation. as @luzrain already mentioned, there is a blog post with more information. in case you find useful information there or discover other things by yourself, it would be very helpful if you can create a pull request and add the information that would have been helpful for you. It will help all others in the future. cheers, Wolfgang
