### ISSUE TITLE
Request to consider adding curl [enhancement]

### ISSUE THREAD

**Issue by mtompkins** [woolfg/mysql-backup-sidecar#12]
Thank you for your work on this handy container.

A fairly straightforward request...please consider adding *curl* to the container so that through the use of your post-script hook, we can communicate with external APIs. For example, I send an API post to a Slack channel that looks much like the following:

`curl -i -X POST -H "Content-Type: application/json" -d "${PAYLOAD}" "${CONN}"`

Giving me a sense of status for the cron job.

**Comment by woolfg** [comment]
I want to keep the base image as small as possible but I fully agree, `curl` is kind of a really basic tool that is needed in a lot of different scenarios. Could you create a pull request with the change in Dockerfile?
