### ISSUE TITLE
Add HOW-IT-WORKS to the README.md

### ISSUE THREAD

**Issue by ACodeDigger** [woolfg/mysql-backup-sidecar#21]
Great job indeed.

Yet I feel like I need some more information while considering applying mysql-backup-sidecar on my production mariadb pod like the followings:
- it reads 'non-blocking' but as far as I concern, it's executing mariabackup --backup then almost the very first query to be executed would be [FLUSH TABLE WITH READ LOCK](https://mariadb.com/kb/en/flush/) so it will definitely block all DML queries while the backup is being done.
- would it be safe to use on InnoDB(storage engine), MyISAM tables while those are being consistently changed.

If I misunderstood, would be very appreciated if you could point it out. Thanks in advance.

**Comment by woolfg** [comment]
Hey @ACodeDigger, thanks for the question. you are right, the underlying software is mariabackup/xtrabackup and there are many edge cases. I think it doesn't make sense to mention all specifics of the backup tools and both tools offer a very extensive documentation. The "non-blocking" approach might be a bit misleading here but is also used as a "marketing term" by xtrabackup itself. This project is "just" a wrapper around the backup tools and for questions about the exact handling/procedures of those tools, I think is better to consult their communities. I close this issue for new, feel free to reopen it.
