### ISSUE TITLE
[HELP] Is there a way to get backup status ?

### ISSUE THREAD

**Issue by guillaumelamirand** [woolfg/mysql-backup-sidecar#3]
Hi,

Thank you again for your work, it is working great.

It is not realy an issue but more asking for same advice.

As the backup is running at night, I would like to get a status of it.
To be more generic, I was thinking of running a script after the bakup.sh or rotate.sh are executed. We could use two variable  SCRIPT_AFTER_BACKUP = "myscript.sh" and SCRIPT_AFTER_ROTATE="myscript2.sh" when launching the container.

I am not realy sure how to obtain a valid status of the backup, how does mariabackup behave in case of errors?

Thank you for your help.
Guillaume

**Comment by woolfg** [comment]
Hey @guillaumelamirand, thanks for the suggestion and idea. A script is a possibility, the question is what you want to achieve? I thin the more common approach is not sending any info about successful  backups but listening for errors on the log stream and trigger a notification in case there was an error.

**Comment by guillaumelamirand** [comment]
I want to call an external api hosted by home assistant to get last backup
status and date, and there I will probably send me a telegram notification
in case of error.
I thought about parsing the log but it requires to setup a cron to
periodically monitor the log while it is required only once a day when
executing the backup.sh.
