### ISSUE TITLE
XTRABACKUP is not in latest version

### ISSUE THREAD

**Issue by Ghost-cruiser** [woolfg/mysql-backup-sidecar#7]
Hi,

First of all thank you for your work. 

I'm using your service with mysql 8.0.21 ; the service is installing xtrabackup 8.0.9 which is not compatible with mysql > 8.0.19 (cf https://www.percona.com/blog/2020/04/28/percona-xtrabackup-8-x-and-mysql-8-0-20/).

As a workaround, I'm able to connect to the machine with "docker exec -it <container-name> bash" in order to update manually the repo, then the xtrabackup install to the version 8.0.14. Of course, each time I'm rebuilding the image, it will pull the 8.0.9 version, forcing me to use my workaround again.

Would it be possible to correct this ? I'm guessing it's juste the "apt update" that is missing from the dockerfile.

In advance, thanks for your attention.

(PS : I'm absolutely not used to Github, if my issue has something missing, feel free to point it to me)

**Comment by woolfg** [comment]
thanks @Ghost-cruiser, I'll have a look asap. In the meanwhile, have you tried to build it from scratch with `make rebuild` or do you just pull the image from docker hub?

**Comment by Ghost-cruiser** [comment]
Sorry for the late answer @woolfg ! No I have only tried from the docker hub's image.

**Comment by woolfg** [comment]
@Ghost-cruiser you can try to clone the project and run `make rebuild` and see if the new image contains the proper version, maybe this solves already your problem.

**Comment by woolfg** [comment]
I rebuilt the docker image and `version 8.0.14 based on MySQL server 8.0.21` is used which should fix this issue. will release a new image v0.3.1 today.
