### ISSUE TITLE
MariaDB 10.5

### ISSUE THREAD

**Issue by luzrain** [woolfg/mysql-backup-sidecar#9]
Can you update MariaDB version to 10.5 ?

**Comment by woolfg** [comment]
@luzrain thanks for the proposal. have you tried it already with 10.5? if you want, you can also send a PR...

**Comment by luzrain** [comment]
#10

**Comment by woolfg** [comment]
image is online https://hub.docker.com/r/woolfg/mysql-backup-sidecar/tags?page=1&ordering=last_updated - thanks @luzrain for the support and contribution
